# coding=utf-8
from django.utils.translation import ugettext as _

_TOPIC_CHOICES = (('', _(u'Selecciona una categoría')),
                (u"agua", u"Agua"),
                (u"asistencia-y-protecci-n-social", u"Asistencia Y Protección Social"),
                (u"ciencias-y-tecnolog-a", u"Ciencias Y Tecnología"),
                (u"cultura-y-deportes", u"Cultura Y Deportes"),
                (u"democracia", u"Democracia"),
                (u"derechos-humanos", u"Derechos Humanos"),
                (u"derechos-sociales", u"Derechos Sociales"),
                (u"descentralizaci-n", u"Descentralización"),
                (u"desastres-naturales", u"Desastres Naturales"),
                (u"desnutrici-n", u"Desnutrición"),
                (u"econom-a-emprendimiento-y-pol-tica-fiscal", u"Economía, Emprendimiento Y Política Fiscal"),
                (u"educaci-n", u"Educación"),
                (u"empleo", u"Empleo"),
                (u"energ-a-renovable", u"Energía Renovable"),
                (u"equidad-y-g-nero", u"Equidad Y Género"),
                (u"inclusi-n-social", u"Inclusión Social"),
                (u"infraestructura", u"Infraestructura"),
                (u"instituciones-p-blicas", u"Instituciones Públicas"),
                (u"infancia-y-juventud", u"Infancia Y Juventud"),
                (u"justicia", u"Justicia"),
                (u"medio-ambiente-y-recursos-naturales", u"Medio Ambiente Y Recursos Naturales"),
                (u"medios-de-comunicaci-n", u"Medios De Comunicación"),
                (u"migraci-n", u"Migración"),
                (u"recreaci-n", u"Recreación"),
                (u"seguridad-social", u"Seguridad Social"),
                (u"participaci-n", u"Participación"),
                (u"previsi-n", u"Previsión"),
                (u"probidad", u"Probidad"),
                (u"pueblos-originarios", u"Pueblos Originarios"),
                (u"salud-p-blica", u"Salud Pública"),
                (u"seguridad", u"Seguridad"),
                (u"servicios-p-blicos-municipales", u"Servicios Públicos Municipales"),
                (u"sustentabilidad", u"Sustentabilidad"),
                (u"adulto-mayor", u"Adulto Mayor"),
                (u"protecci-n-animal", u"Protección Animal"),
                (u"trabajo", u"Trabajo"),
                (u"transporte-p-blico", u"Transporte Público"),
                (u"lucha-contra-la-corrupci-n", u"Lucha Contra La Corrupción"),
                (u"urbanismo", u"Urbanismo"),
                (u"espacios-p-blicos", u"Espacios Públicos"),
)
